- name: Install Composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer creates=/usr/local/bin/composer

- name: Add token for github
  shell: composer config -g github-oauth.github.com f6124ac168449608bd74c2b88cb67a0c2ae3b1df


- name: Install asset extension
  shell: composer global require "fxp/composer-asset-plugin:~1.1.1"
